
version: 2

models:
  - name: test
    description: "A starter dbt model"
    columns:
      - name: name
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
